from enum import Enum


class GenderTypeEnum(Enum):
    MR = "MR"
    MRS = "MRS"
    MS = "MS"


class WeatherTypeEnum(Enum):
    DRY = "DRY"
    RAINY = "RAINY"
    STROMY = "STROMY"
    CLOUDY = "CLOUDY"
    SUNNY = "SUNNY"

class PersonRoleEnum(Enum):
    CLIENT = "CLIENT"
    PASSENGER = "PASSENGER"
    WITNESS = "WITNESS"

class CountryCodeEnum(Enum):
    AF = "AF"
    AL = "AL"
    DZ = "DZ"
    AD = "AD"
    AO = "AO"
    AG = "AG"
    AR = "AR"
    AM = "AM"
    AU = "AU"
    AT = "AT"
    AZ = "AZ"
    BS = "BS"
    BH = "BH"
    BD = "BD"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    BZ = "BZ"
    BJ = "BJ"
    BT = "BT"
    BO = "BO"
    BA = "BA"
    BW = "BW"
    BR = "BR"
    BN = "BN"
    BG = "BG"
    BF = "BF"
    BI = "BI"
    CV = "CV"
    KH = "KH"
    CM = "CM"
    CA = "CA"
    CF = "CF"
    TD = "TD"
    CL = "CL"
    CN = "CN"
    CO = "CO"
    KM = "KM"
    CG = "CG"
    CD = "CD"
    CR = "CR"
    HR = "HR"
    CU = "CU"
    CY = "CY"
    CZ = "CZ"
    DK = "DK"
    DJ = "DJ"
    DM = "DM"
    DO = "DO"
    EC = "EC"
    EG = "EG"
    SV = "SV"
    GQ = "GQ"
    ER = "ER"
    EE = "EE"
    SZ = "SZ"
    ET = "ET"
    FJ = "FJ"
    FI = "FI"
    FR = "FR"
    GA = "GA"
    GM = "GM"
    GE = "GE"
    DE = "DE"
    GH = "GH"
    GR = "GR"
    GD = "GD"
    GT = "GT"
    GN = "GN"
    GW = "GW"
    GY = "GY"
    HT = "HT"
    HN = "HN"
    HU = "HU"
    IS = "IS"
    IN = "IN"
    ID = "ID"
    IR = "IR"
    IQ = "IQ"
    IE = "IE"
    IL = "IL"
    IT = "IT"
    JM = "JM"
    JP = "JP"
    JO = "JO"
    KZ = "KZ"
    KE = "KE"
    KI = "KI"
    KP = "KP"
    KR = "KR"
    KW = "KW"
    KG = "KG"
    LA = "LA"
    LV = "LV"
    LB = "LB"
    LS = "LS"
    LR = "LR"
    LY = "LY"
    LI = "LI"
    LT = "LT"
    LU = "LU"
    MG = "MG"
    MW = "MW"
    MY = "MY"
    MV = "MV"
    ML = "ML"
    MT = "MT"
    MH = "MH"
    MR = "MR"
    MU = "MU"
    MX = "MX"
    FM = "FM"
    MD = "MD"
    MC = "MC"
    MN = "MN"
    ME = "ME"
    MA = "MA"
    MZ = "MZ"
    MM = "MM"
    NA = "NA"
    NR = "NR"
    NP = "NP"
    NL = "NL"
    NZ = "NZ"
    NI = "NI"
    NE = "NE"
    NG = "NG"
    MK = "MK"
    NO = "NO"
    OM = "OM"
    PK = "PK"
    PW = "PW"
    PA = "PA"
    PG = "PG"
    PY = "PY"
    PE = "PE"
    PH = "PH"
    PL = "PL"
    PT = "PT"
    QA = "QA"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    KN = "KN"
    LC = "LC"
    VC = "VC"
    WS = "WS"
    SM = "SM"
    ST = "ST"
    SA = "SA"
    SN = "SN"
    RS = "RS"
    SC = "SC"
    SL = "SL"
    SG = "SG"
    SX = "SX"
    SK = "SK"
    SI = "SI"
    SB = "SB"
    SO = "SO"
    ZA = "ZA"
    SS = "SS"
    ES = "ES"
    LK = "LK"
    SD = "SD"
    SR = "SR"
    SE = "SE"
    CH = "CH"
    SY = "SY"
    TW = "TW"
    TJ = "TJ"
    TZ = "TZ"
    TH = "TH"
    TG = "TG"
    TO = "TO"
    TT = "TT"
    TN = "TN"
    TM = "TM"
    TR = "TR"
    TV = "TV"
    UG = "UG"
    UA = "UA"
    AE = "AE"
    UK = "UK"
    US = "US"
    UY = "UY"
    UZ = "UZ"
    VU = "VU"
    VA = "VA"
    VE = "VE"
    VN = "VN"
    YE = "YE"
    ZM = "ZM"
    ZW = "ZW"


class CurrencyTypeEnum(str, Enum):
    AED = "AED"  # UAE Dirham
    AFN = "AFN"  # Afghan Afghani
    ALL = "ALL"  # Albanian Lek
    AMD = "AMD"  # Armenian Dram
    ANG = "ANG"  # Netherlands Antillean Guilder
    AOA = "AOA"  # Angolan Kwanza
    ARS = "ARS"  # Argentine Peso
    AUD = "AUD"  # Australian Dollar
    AWG = "AWG"  # Aruban Florin
    AZN = "AZN"  # Azerbaijani Manat
    BAM = "BAM"  # Bosnia-Herzegovina Convertible Mark
    BBD = "BBD"  # Barbadian Dollar
    BDT = "BDT"  # Bangladeshi Taka
    BGN = "BGN"  # Bulgarian Lev
    BHD = "BHD"  # Bahraini Dinar
    BIF = "BIF"  # Burundian Franc
    BMD = "BMD"  # Bermudian Dollar
    BND = "BND"  # Brunei Dollar
    BOB = "BOB"  # Bolivian Boliviano
    BRL = "BRL"  # Brazilian Real
    BSD = "BSD"  # Bahamian Dollar
    BTN = "BTN"  # Bhutanese Ngultrum
    BWP = "BWP"  # Botswana Pula
    BYN = "BYN"  # Belarusian Ruble
    BZD = "BZD"  # Belize Dollar
    CAD = "CAD"  # Canadian Dollar
    CDF = "CDF"  # Congolese Franc
    CHF = "CHF"  # Swiss Franc
    CLP = "CLP"  # Chilean Peso
    CNY = "CNY"  # Chinese Yuan
    COP = "COP"  # Colombian Peso
    CRC = "CRC"  # Costa Rican Colón
    CUP = "CUP"  # Cuban Peso
    CVE = "CVE"  # Cape Verdean Escudo
    CZK = "CZK"  # Czech Koruna
    DJF = "DJF"  # Djiboutian Franc
    DKK = "DKK"  # Danish Krone
    DOP = "DOP"  # Dominican Peso
    DZD = "DZD"  # Algerian Dinar
    EGP = "EGP"  # Egyptian Pound
    ERN = "ERN"  # Eritrean Nakfa
    ETB = "ETB"  # Ethiopian Birr
    EUR = "EUR"  # Euro
    FJD = "FJD"  # Fijian Dollar
    FKP = "FKP"  # Falkland Islands Pound
    FOK = "FOK"  # Faroese Króna
    GBP = "GBP"  # British Pound Sterling
    GEL = "GEL"  # Georgian Lari
    GGP = "GGP"  # Guernsey Pound
    GHS = "GHS"  # Ghanaian Cedi
    GIP = "GIP"  # Gibraltar Pound
    GMD = "GMD"  # Gambian Dalasi
    GNF = "GNF"  # Guinean Franc
    GTQ = "GTQ"  # Guatemalan Quetzal
    GYD = "GYD"  # Guyanaese Dollar
    HKD = "HKD"  # Hong Kong Dollar
    HNL = "HNL"  # Honduran Lempira
    HRK = "HRK"  # Croatian Kuna
    HTG = "HTG"  # Haitian Gourde
    HUF = "HUF"  # Hungarian Forint
    IDR = "IDR"  # Indonesian Rupiah
    ILS = "ILS"  # Israeli New Shekel
    IMP = "IMP"  # Isle of Man Pound
    INR = "INR"  # Indian Rupee
    IQD = "IQD"  # Iraqi Dinar
    IRR = "IRR"  # Iranian Rial
    ISK = "ISK"  # Icelandic Króna
    JEP = "JEP"  # Jersey Pound
    JMD = "JMD"  # Jamaican Dollar
    JOD = "JOD"  # Jordanian Dinar
    JPY = "JPY"  # Japanese Yen
    KES = "KES"  # Kenyan Shilling
    KGS = "KGS"  # Kyrgyzstani Som
    KHR = "KHR"  # Cambodian Riel
    KID = "KID"  # Kiribati Dollar
    KMF = "KMF"  # Comorian Franc
    KRW = "KRW"  # South Korean Won
    KWD = "KWD"  # Kuwaiti Dinar
    KYD = "KYD"  # Cayman Islands Dollar
    KZT = "KZT"  # Kazakhstani Tenge
    LAK = "LAK"  # Lao Kip
    LBP = "LBP"  # Lebanese Pound
    LKR = "LKR"  # Sri Lankan Rupee
    LRD = "LRD"  # Liberian Dollar
    LSL = "LSL"  # Lesotho Loti
    LYD = "LYD"  # Libyan Dinar
    MAD = "MAD"  # Moroccan Dirham
    MDL = "MDL"  # Moldovan Leu
    MGA = "MGA"  # Malagasy Ariary
    MKD = "MKD"  # Macedonian Denar
    MMK = "MMK"  # Myanmar Kyat
    MNT = "MNT"  # Mongolian Tögrög
    MOP = "MOP"  # Macanese Pataca
    MRU = "MRU"  # Mauritanian Ouguiya
    MUR = "MUR"  # Mauritian Rupee
    MVR = "MVR"  # Maldivian Rufiyaa
    MWK = "MWK"  # Malawian Kwacha
    MXN = "MXN"  # Mexican Peso
    MYR = "MYR"  # Malaysian Ringgit
    MZN = "MZN"  # Mozambican Metical
    NAD = "NAD"  # Namibian Dollar
    NGN = "NGN"  # Nigerian Naira
    NIO = "NIO"  # Nicaraguan Córdoba
    NOK = "NOK"  # Norwegian Krone
    NPR = "NPR"  # Nepalese Rupee
    NZD = "NZD"  # New Zealand Dollar
    OMR = "OMR"  # Omani Rial
    PAB = "PAB"  # Panamanian Balboa
    PEN = "PEN"  # Peruvian Sol
    PGK = "PGK"  # Papua New Guinean Kina
    PHP = "PHP"  # Philippine Peso
    PKR = "PKR"  # Pakistani Rupee
    PLN = "PLN"  # Polish Złoty
    PYG = "PYG"  # Paraguayan Guaraní
    QAR = "QAR"  # Qatari Riyal
    RON = "RON"  # Romanian Leu
    RSD = "RSD"  # Serbian Dinar
    RUB = "RUB"  # Russian Ruble
    RWF = "RWF"  # Rwandan Franc
    SAR = "SAR"  # Saudi Riyal
    SBD = "SBD"  # Solomon Islands Dollar
    SCR = "SCR"  # Seychellois Rupee
    SDG = "SDG"  # Sudanese Pound
    SEK = "SEK"  # Swedish Krona
    SGD = "SGD"  # Singapore Dollar
    SHP = "SHP"  # Saint Helena Pound
    SLE = "SLE"  # Sierra Leonean Leone
    SOS = "SOS"  # Somali Shilling
    SRD = "SRD"  # Surinamese Dollar
    SSP = "SSP"  # South Sudanese Pound
    STN = "STN"  # São Tomé and Príncipe Dobra
    SYP = "SYP"  # Syrian Pound
    SZL = "SZL"  # Eswatini Lilangeni
    THB = "THB"  # Thai Baht
    TJS = "TJS"  # Tajikistani Somoni
    TMT = "TMT"  # Turkmenistani Manat
    TND = "TND"  # Tunisian Dinar
    TOP = "TOP"  # Tongan Paʻanga
    TRY = "TRY"  # Turkish Lira
    TTD = "TTD"  # Trinidad and Tobago Dollar
    TVD = "TVD"  # Tuvaluan Dollar
    TWD = "TWD"  # New Taiwan Dollar
    TZS = "TZS"  # Tanzanian Shilling
    UAH = "UAH"  # Ukrainian Hryvnia
    UGX = "UGX"  # Ugandan Shilling
    USD = "USD"  # United States Dollar
    UYU = "UYU"  # Uruguayan Peso
    UZS = "UZS"  # Uzbekistani Soʻm
    VES = "VES"  # Venezuelan Bolívar
    VND = "VND"  # Vietnamese Đồng
    VUV = "VUV"  # Vanuatu Vatu
    WST = "WST"  # Samoan Tālā
    XAF = "XAF"  # Central African CFA Franc
    XCD = "XCD"  # East Caribbean Dollar
    XOF = "XOF"  # West African CFA Franc
    XPF = "XPF"  # CFP Franc
    YER = "YER"  # Yemeni Rial
    ZAR = "ZAR"  # South African Rand
    ZMW = "ZMW"  # Zambian Kwacha
    ZWL = "ZWL"  # Zimbabwean Dollar
