"""update tables and add language table

Revision ID: 0546a4ebd50c
Revises: ce6685e98d64
Create Date: 2025-08-25 03:58:45.500525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0546a4ebd50c'
down_revision: Union[str, None] = 'ce6685e98d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_created_by'), 'languages', ['created_by'], unique=False)
    op.create_index(op.f('ix_languages_tenant_id'), 'languages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_languages_updated_by'), 'languages', ['updated_by'], unique=False)
    op.add_column('client_details', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_client_details_language_id'), 'client_details', ['language_id'], unique=False)
    op.create_foreign_key(None, 'client_details', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.drop_column('client_details', 'client_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_details', sa.Column('client_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client_details', type_='foreignkey')
    op.drop_index(op.f('ix_client_details_language_id'), table_name='client_details')
    op.drop_column('client_details', 'language_id')
    op.drop_index(op.f('ix_languages_updated_by'), table_name='languages')
    op.drop_index(op.f('ix_languages_tenant_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_created_by'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
