"""sync all model changes

Revision ID: 1a2419bd4a97
Revises: 4d9cb5e37c10
Create Date: 2026-02-17 20:09:43.717119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2419bd4a97'
down_revision: Union[str, None] = '4d9cb5e37c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accident_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('accident_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('accident_details', 'date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('accident_details', 'condition',
               existing_type=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               nullable=True)
    op.alter_column('accident_details', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accident_details', 'service_date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('accident_details', 'any_passenger',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'witness',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'police_attend',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'dash_footage',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accident_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('addresses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('addresses', 'postcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('addresses', 'mobile_tel',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('addresses', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('borough', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('borough', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('borough', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('borough', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('borough', 'client_vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('borough', 'borough_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('borough', 'client_badge_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('borough', 'badge_expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('borough', 'vehicle_badge_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('case_statuses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('case_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_statuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_statuses', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('case_statuses', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('case_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_questionnaires', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claim_questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('claims', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'file_opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'client_going_abroad',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'PASSENGER', 'WITNESS', name='personroleenum'),
               nullable=True)
    op.alter_column('client_details', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('client_details', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('client_details', 'surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('client_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_details', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_details', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'client_details', ['ni_number'])
    op.create_unique_constraint(None, 'client_details', ['account_number'])
    op.alter_column('client_vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_vehicles', 'make',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('client_vehicles', 'model',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('client_vehicles', 'body_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('client_vehicles', 'registration',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('client_vehicles', 'engine_size',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('client_vehicles', 'number_of_seat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_vehicles', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('driver_commissions', 'currency',
               existing_type=postgresql.ENUM('AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'FOK', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KID', 'KMF', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SOS', 'SRD', 'SSP', 'STN', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TVD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMW', 'ZWL', name='currencytypeenum'),
               nullable=True)
    op.alter_column('driver_commissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fuel_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fuel_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fuel_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fuel_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('fuel_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fuel_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('handlers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('handlers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('handlers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('handlers', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('handlers', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('handlers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('languages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('languages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('languages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('police_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('police_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('police_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_details', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('police_details', 'reference_no',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('police_details', 'station_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('police_details', 'station_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('police_details', 'incident_report_taken',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('police_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('present_file_positions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('present_file_positions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('present_file_positions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('present_file_positions', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('present_file_positions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('present_file_positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('prospects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('prospects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prospects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prospects', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('prospects', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prospects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questionnaires', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questionnaires', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questionnaires', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questionnaires', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questionnaires', 'question',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('questionnaires', 'answer',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('referrer_commissions', 'currency',
               existing_type=postgresql.ENUM('AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'FOK', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KID', 'KMF', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SOS', 'SRD', 'SSP', 'STN', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TVD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMW', 'ZWL', name='currencytypeenum'),
               nullable=True)
    op.alter_column('referrer_commissions', 'on_hire_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('referrer_commissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrers', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrers', 'country',
               existing_type=postgresql.ENUM('AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KH', 'CM', 'CA', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CR', 'HR', 'CU', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TO', 'TT', 'TN', 'TM', 'TR', 'TV', 'UG', 'UA', 'AE', 'UK', 'US', 'UY', 'UZ', 'VU', 'VA', 'VE', 'VN', 'YE', 'ZM', 'ZW', name='country_code_enum'),
               nullable=True)
    op.alter_column('referrers', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('referrers', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('referrers', 'solicitor',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('referrers', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrers', 'primary_contact_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('referrers', 'third_party_capture',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('referrers', 'driver_commission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrers', 'referrer_commission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('source_channels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('source_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_channels', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('source_channels', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('source_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('source_channels', 'requires_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('target_debts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('target_debts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('target_debts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('target_debts', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('target_debts', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('target_debts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('taxi_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('taxi_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('taxi_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('taxi_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('taxi_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxi_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('third_party_vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('third_party_vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('third_party_vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('third_party_vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('third_party_vehicles', 'client_vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('third_party_vehicles', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('third_party_vehicles', 'make',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('third_party_vehicles', 'model',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('third_party_vehicles', 'registration',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('third_party_vehicles', 'images_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('transmissions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('transmissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transmissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transmissions', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('transmissions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transmissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('transmissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('transmissions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transmissions', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('transmissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transmissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transmissions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('third_party_vehicles', 'images_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('third_party_vehicles', 'registration',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('third_party_vehicles', 'model',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('third_party_vehicles', 'make',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('third_party_vehicles', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('third_party_vehicles', 'client_vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('third_party_vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('third_party_vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('third_party_vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('third_party_vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('taxi_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('taxi_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxi_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('taxi_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('taxi_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('taxi_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('target_debts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('target_debts', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('target_debts', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('target_debts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('target_debts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('target_debts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('source_channels', 'requires_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('source_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('source_channels', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('source_channels', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('source_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_channels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('referrers', 'referrer_commission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrers', 'driver_commission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrers', 'third_party_capture',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('referrers', 'primary_contact_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('referrers', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrers', 'solicitor',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('referrers', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('referrers', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('referrers', 'country',
               existing_type=postgresql.ENUM('AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KH', 'CM', 'CA', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CR', 'HR', 'CU', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TO', 'TT', 'TN', 'TM', 'TR', 'TV', 'UG', 'UA', 'AE', 'UK', 'US', 'UY', 'UZ', 'VU', 'VA', 'VE', 'VN', 'YE', 'ZM', 'ZW', name='country_code_enum'),
               nullable=False)
    op.alter_column('referrers', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrer_commissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrer_commissions', 'on_hire_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('referrer_commissions', 'currency',
               existing_type=postgresql.ENUM('AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'FOK', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KID', 'KMF', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SOS', 'SRD', 'SSP', 'STN', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TVD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMW', 'ZWL', name='currencytypeenum'),
               nullable=False)
    op.alter_column('questionnaires', 'answer',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('questionnaires', 'question',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('questionnaires', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questionnaires', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('questionnaires', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('questionnaires', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prospects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prospects', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prospects', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('prospects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prospects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prospects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('present_file_positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('present_file_positions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('present_file_positions', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('present_file_positions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('present_file_positions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('present_file_positions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('police_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('police_details', 'incident_report_taken',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('police_details', 'station_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('police_details', 'station_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('police_details', 'reference_no',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('police_details', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('police_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('police_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('languages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('languages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('languages', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('languages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('handlers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('handlers', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('handlers', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('handlers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('handlers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('handlers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fuel_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fuel_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fuel_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('fuel_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fuel_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fuel_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('driver_commissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('driver_commissions', 'currency',
               existing_type=postgresql.ENUM('AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'FOK', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KID', 'KMF', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SOS', 'SRD', 'SSP', 'STN', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TVD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMW', 'ZWL', name='currencytypeenum'),
               nullable=False)
    op.alter_column('client_vehicles', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_vehicles', 'number_of_seat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_vehicles', 'engine_size',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('client_vehicles', 'registration',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('client_vehicles', 'body_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('client_vehicles', 'model',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('client_vehicles', 'make',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('client_vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_vehicles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'client_details', type_='unique')
    op.drop_constraint(None, 'client_details', type_='unique')
    op.alter_column('client_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_details', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_details', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_details', 'surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('client_details', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('client_details', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('client_details', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'PASSENGER', 'WITNESS', name='personroleenum'),
               nullable=False)
    op.alter_column('client_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('claims', 'client_going_abroad',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'file_opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claims', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_types', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('claim_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_types', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_questionnaires', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('claim_questionnaires', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('case_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('case_statuses', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('case_statuses', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('case_statuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_statuses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('borough', 'vehicle_badge_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('borough', 'badge_expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('borough', 'client_badge_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('borough', 'borough_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('borough', 'client_vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('borough', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('borough', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('borough', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('borough', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('addresses', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresses', 'mobile_tel',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('addresses', 'postcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('addresses', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accident_details', 'dash_footage',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'police_attend',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'witness',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'any_passenger',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'service_date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('accident_details', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accident_details', 'condition',
               existing_type=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               nullable=False)
    op.alter_column('accident_details', 'date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('accident_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accident_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accident_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accident_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
