"""add created_at and updated_at to client_details

Revision ID: 24ed5fff34ee
Revises: 4661edb1511d
Create Date: 2025-09-11 18:19:12.088204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ed5fff34ee'
down_revision: Union[str, None] = '4661edb1511d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
