"""add questionnaire table

Revision ID: 2be1760b7e48
Revises: d5b7117504ef
Create Date: 2025-09-05 14:15:50.922809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be1760b7e48'
down_revision: Union[str, None] = 'd5b7117504ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=2000), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_claim_id'), 'questionnaires', ['claim_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_created_by'), 'questionnaires', ['created_by'], unique=False)
    op.create_index(op.f('ix_questionnaires_id'), 'questionnaires', ['id'], unique=False)
    op.create_index(op.f('ix_questionnaires_updated_by'), 'questionnaires', ['updated_by'], unique=False)
    op.create_index(op.f('ix_questionnaires_user_id'), 'questionnaires', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaires_user_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_updated_by'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_created_by'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_claim_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
