"""Added witness clumns

Revision ID: 4661edb1511d
Revises: 73417fda7e04
Create Date: 2025-09-09 04:28:22.101874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4661edb1511d'
down_revision: Union[str, None] = '73417fda7e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_details', sa.Column('witness_independent', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('client_details_account_number_key'), 'client_details', type_='unique')
    op.drop_constraint(op.f('client_details_ni_number_key'), 'client_details', type_='unique')
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('client_details_ni_number_key'), 'client_details', ['ni_number'])
    op.create_unique_constraint(op.f('client_details_account_number_key'), 'client_details', ['account_number'])
    op.drop_column('client_details', 'witness_independent')
    # ### end Alembic commands ###
