"""sync all model changes

Revision ID: 473e36ff398a
Revises: 7154d934b931
Create Date: 2026-02-22 00:35:30.354248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473e36ff398a'
down_revision: Union[str, None] = '7154d934b931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accident_details', 'condition',
               existing_type=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accident_details', 'condition',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
