"""sync all model changes

Revision ID: 4d9cb5e37c10
Revises: a8ad4eac0490
Create Date: 2026-02-17 20:08:20.771900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9cb5e37c10'
down_revision: Union[str, None] = 'a8ad4eac0490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claim_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_types', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
