"""vehicle detail

Revision ID: 598e15b0a93f
Revises: 0546a4ebd50c
Create Date: 2025-08-27 04:57:04.543563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e15b0a93f'
down_revision: Union[str, None] = '0546a4ebd50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fuel_types',
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_types_created_by'), 'fuel_types', ['created_by'], unique=False)
    op.create_index(op.f('ix_fuel_types_tenant_id'), 'fuel_types', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fuel_types_updated_by'), 'fuel_types', ['updated_by'], unique=False)

    op.create_table(
        'taxi_types',
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_types_created_by'), 'taxi_types', ['created_by'], unique=False)
    op.create_index(op.f('ix_taxi_types_tenant_id'), 'taxi_types', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_taxi_types_updated_by'), 'taxi_types', ['updated_by'], unique=False)

    op.create_table(
        'transmissions',
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmissions_created_by'), 'transmissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_transmissions_tenant_id'), 'transmissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transmissions_updated_by'), 'transmissions', ['updated_by'], unique=False)

    op.create_table(
        'client_vehicles',
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('make', sa.String(length=200), nullable=False),
        sa.Column('model', sa.String(length=200), nullable=False),
        sa.Column('body_type', sa.String(length=200), nullable=False),
        sa.Column('registration', sa.String(length=200), nullable=False),
        sa.Column('color', sa.String(length=200), nullable=True),
        sa.Column('fuel_type_id', sa.Integer(), nullable=True),
        sa.Column('engine_size', sa.String(length=200), nullable=False),
        sa.Column('transmission_id', sa.Integer(), nullable=True),
        sa.Column('number_of_seat', sa.Integer(), nullable=False),
        sa.Column('vehicle_category', sa.String(length=200), nullable=True),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('claim_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_vehicles_claim_id'), 'client_vehicles', ['claim_id'], unique=False)
    op.create_index(op.f('ix_client_vehicles_created_by'), 'client_vehicles', ['created_by'], unique=False)
    op.create_index(op.f('ix_client_vehicles_fuel_type_id'), 'client_vehicles', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_client_vehicles_tenant_id'), 'client_vehicles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_client_vehicles_transmission_id'), 'client_vehicles', ['transmission_id'], unique=False)
    op.create_index(op.f('ix_client_vehicles_updated_by'), 'client_vehicles', ['updated_by'], unique=False)

    # ---- ENUM CREATION FIX ----
    country_code_enum = sa.Enum(
        'AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
        'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
        'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KH', 'CM', 'CA', 'CF',
        'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CR', 'HR', 'CU', 'CY',
        'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE',
        'SZ', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
        'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
        'IR', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI',
        'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI',
        'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU',
        'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR',
        'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW',
        'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW',
        'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL',
        'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD',
        'SR', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TO', 'TT',
        'TN', 'TM', 'TR', 'TV', 'UG', 'UA', 'AE', 'UK', 'US', 'UY', 'UZ',
        'VU', 'VA', 'VE', 'VN', 'YE', 'ZM', 'ZW',
        name="country_code_enum"
    )
    currency_enum = sa.Enum(
        'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN',
        'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL',
        'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY',
        'COP', 'CRC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP',
        'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'FOK', 'GBP', 'GEL', 'GGP', 'GHS',
        'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF',
        'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD',
        'JPY', 'KES', 'KGS', 'KHR', 'KID', 'KMF', 'KRW', 'KWD', 'KYD', 'KZT',
        'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD',
        'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN',
        'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK',
        'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR',
        'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SOS', 'SRD', 'SSP',
        'STN', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD',
        'TVD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VES', 'VND',
        'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMW', 'ZWL',
        name="currencytypeenum"
    )

    # Create ENUMs before adding columns
    country_code_enum.create(op.get_bind(), checkfirst=True)
    currency_enum.create(op.get_bind(), checkfirst=True)

    # Now add columns using ENUMs
    op.add_column('client_details', sa.Column('country', country_code_enum, nullable=False))
    op.add_column('driver_commissions', sa.Column('currency', currency_enum, nullable=False))
    op.add_column('referrer_commissions', sa.Column('currency', currency_enum, nullable=False))
    op.add_column('referrers', sa.Column('country', country_code_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop enum columns first
    op.drop_column('referrers', 'country')
    op.drop_column('referrer_commissions', 'currency')
    op.drop_column('driver_commissions', 'currency')
    op.drop_column('client_details', 'country')

    # Drop tables (auto-generated)
    op.drop_index(op.f('ix_third_party_vehicles_updated_by'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_id'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_created_by'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_client_vehicle_id'), table_name='third_party_vehicles')
    op.drop_table('third_party_vehicles')
    op.drop_index(op.f('ix_borough_updated_by'), table_name='borough')
    op.drop_index(op.f('ix_borough_tenant_id'), table_name='borough')
    op.drop_index(op.f('ix_borough_taxi_type_id'), table_name='borough')
    op.drop_index(op.f('ix_borough_created_by'), table_name='borough')
    op.drop_index(op.f('ix_borough_client_vehicle_id'), table_name='borough')
    op.drop_table('borough')
    op.drop_index(op.f('ix_client_vehicles_updated_by'), table_name='client_vehicles')
    op.drop_index(op.f('ix_client_vehicles_transmission_id'), table_name='client_vehicles')
    op.drop_index(op.f('ix_client_vehicles_tenant_id'), table_name='client_vehicles')
    op.drop_index(op.f('ix_client_vehicles_fuel_type_id'), table_name='client_vehicles')
    op.drop_index(op.f('ix_client_vehicles_created_by'), table_name='client_vehicles')
    op.drop_index(op.f('ix_client_vehicles_claim_id'), table_name='client_vehicles')
    op.drop_table('client_vehicles')
    op.drop_index(op.f('ix_transmissions_updated_by'), table_name='transmissions')
    op.drop_index(op.f('ix_transmissions_tenant_id'), table_name='transmissions')
    op.drop_index(op.f('ix_transmissions_created_by'), table_name='transmissions')
    op.drop_table('transmissions')
    op.drop_index(op.f('ix_taxi_types_updated_by'), table_name='taxi_types')
    op.drop_index(op.f('ix_taxi_types_tenant_id'), table_name='taxi_types')
    op.drop_index(op.f('ix_taxi_types_created_by'), table_name='taxi_types')
    op.drop_table('taxi_types')
    op.drop_index(op.f('ix_fuel_types_updated_by'), table_name='fuel_types')
    op.drop_index(op.f('ix_fuel_types_tenant_id'), table_name='fuel_types')
    op.drop_index(op.f('ix_fuel_types_created_by'), table_name='fuel_types')
    op.drop_table('fuel_types')

    # Finally drop ENUM types
    sa.Enum(name="currencytypeenum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="country_code_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
