"""Added created at for claim questionairess

Revision ID: 73417fda7e04
Revises: 0db3b509dda8
Create Date: 2025-09-09 03:29:04.382274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73417fda7e04'
down_revision: Union[str, None] = '0db3b509dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_questionnaires', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('claim_questionnaires', 'created_at')
    # ### end Alembic commands ###
