"""sync_all_model_changes

Revision ID: 7346658a9075
Revises: 652f44db2673
Create Date: 2026-03-12 13:50:58.961124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7346658a9075'
down_revision: Union[str, None] = '652f44db2673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_companies_updated_by', 'companies', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_companies_created_by', 'companies', 'users', ['created_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_companies_created_by', 'companies', type_='foreignkey')
    op.drop_constraint('fk_companies_updated_by', 'companies', type_='foreignkey')
    # ### end Alembic commands ###
