"""claims tables

Revision ID: 950dd262a77d
Revises: 7061118c828f
Create Date: 2025-08-10 23:38:55.918149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950dd262a77d'
down_revision: Union[str, None] = '7061118c828f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_statuses_created_by'), 'case_statuses', ['created_by'], unique=False)
    op.create_index(op.f('ix_case_statuses_tenant_id'), 'case_statuses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_case_statuses_updated_by'), 'case_statuses', ['updated_by'], unique=False)
    op.create_table('claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_types_created_by'), 'claim_types', ['created_by'], unique=False)
    op.create_index(op.f('ix_claim_types_tenant_id'), 'claim_types', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_claim_types_updated_by'), 'claim_types', ['updated_by'], unique=False)
    op.create_table('handlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handlers_created_by'), 'handlers', ['created_by'], unique=False)
    op.create_index(op.f('ix_handlers_tenant_id'), 'handlers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_handlers_updated_by'), 'handlers', ['updated_by'], unique=False)
    op.create_table('present_file_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_present_file_positions_created_by'), 'present_file_positions', ['created_by'], unique=False)
    op.create_index(op.f('ix_present_file_positions_tenant_id'), 'present_file_positions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_present_file_positions_updated_by'), 'present_file_positions', ['updated_by'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_created_by'), 'prospects', ['created_by'], unique=False)
    op.create_index(op.f('ix_prospects_tenant_id'), 'prospects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_prospects_updated_by'), 'prospects', ['updated_by'], unique=False)
    op.create_table('source_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_staff', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_channels_created_by'), 'source_channels', ['created_by'], unique=False)
    op.create_index(op.f('ix_source_channels_tenant_id'), 'source_channels', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_source_channels_updated_by'), 'source_channels', ['updated_by'], unique=False)
    op.create_table('target_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_debts_created_by'), 'target_debts', ['created_by'], unique=False)
    op.create_index(op.f('ix_target_debts_tenant_id'), 'target_debts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_target_debts_updated_by'), 'target_debts', ['updated_by'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_type_id', sa.Integer(), nullable=True),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('target_debt_id', sa.Integer(), nullable=True),
    sa.Column('case_status_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_staff_user_id', sa.Integer(), nullable=True),
    sa.Column('prospects_id', sa.Integer(), nullable=True),
    sa.Column('entrant_user_id', sa.Integer(), nullable=True),
    sa.Column('present_position_id', sa.Integer(), nullable=True),
    sa.Column('credit_hire_accepted', sa.Boolean(), nullable=True),
    sa.Column('non_fault_accident', sa.String(length=8), nullable=True),
    sa.Column('any_passengers', sa.String(length=8), nullable=True),
    sa.Column('client_injured', sa.String(length=8), nullable=True),
    sa.Column('file_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_closed_reason', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('client_going_abroad', sa.Boolean(), nullable=False),
    sa.Column('abroad_date', sa.Date(), nullable=True),
    sa.Column('manager_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_status_id'], ['case_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_type_id'], ['claim_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entrant_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['present_position_id'], ['present_file_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prospects_id'], ['prospects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_staff_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_debt_id'], ['target_debts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_case_status_id'), 'claims', ['case_status_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_type_id'), 'claims', ['claim_type_id'], unique=False)
    op.create_index(op.f('ix_claims_created_by'), 'claims', ['created_by'], unique=False)
    op.create_index(op.f('ix_claims_entrant_user_id'), 'claims', ['entrant_user_id'], unique=False)
    op.create_index(op.f('ix_claims_handler_id'), 'claims', ['handler_id'], unique=False)
    op.create_index(op.f('ix_claims_present_position_id'), 'claims', ['present_position_id'], unique=False)
    op.create_index(op.f('ix_claims_prospects_id'), 'claims', ['prospects_id'], unique=False)
    op.create_index(op.f('ix_claims_source_id'), 'claims', ['source_id'], unique=False)
    op.create_index(op.f('ix_claims_source_staff_user_id'), 'claims', ['source_staff_user_id'], unique=False)
    op.create_index(op.f('ix_claims_target_debt_id'), 'claims', ['target_debt_id'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_claims_updated_by'), 'claims', ['updated_by'], unique=False)
    op.drop_constraint('tenants_name_key', 'tenants', type_='unique')
    op.drop_constraint('fk_tenants_created_by_users', 'tenants', type_='foreignkey')
    op.drop_constraint('fk_tenants_updated_by_users', 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tenants', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key('fk_tenants_updated_by_users', 'tenants', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_tenants_created_by_users', 'tenants', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('tenants_name_key', 'tenants', ['name'])
    op.drop_index(op.f('ix_claims_updated_by'), table_name='claims')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_target_debt_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_source_staff_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_source_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_prospects_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_present_position_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_handler_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_entrant_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_created_by'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_status_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_target_debts_updated_by'), table_name='target_debts')
    op.drop_index(op.f('ix_target_debts_tenant_id'), table_name='target_debts')
    op.drop_index(op.f('ix_target_debts_created_by'), table_name='target_debts')
    op.drop_table('target_debts')
    op.drop_index(op.f('ix_source_channels_updated_by'), table_name='source_channels')
    op.drop_index(op.f('ix_source_channels_tenant_id'), table_name='source_channels')
    op.drop_index(op.f('ix_source_channels_created_by'), table_name='source_channels')
    op.drop_table('source_channels')
    op.drop_index(op.f('ix_prospects_updated_by'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_tenant_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_created_by'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_present_file_positions_updated_by'), table_name='present_file_positions')
    op.drop_index(op.f('ix_present_file_positions_tenant_id'), table_name='present_file_positions')
    op.drop_index(op.f('ix_present_file_positions_created_by'), table_name='present_file_positions')
    op.drop_table('present_file_positions')
    op.drop_index(op.f('ix_handlers_updated_by'), table_name='handlers')
    op.drop_index(op.f('ix_handlers_tenant_id'), table_name='handlers')
    op.drop_index(op.f('ix_handlers_created_by'), table_name='handlers')
    op.drop_table('handlers')
    op.drop_index(op.f('ix_claim_types_updated_by'), table_name='claim_types')
    op.drop_index(op.f('ix_claim_types_tenant_id'), table_name='claim_types')
    op.drop_index(op.f('ix_claim_types_created_by'), table_name='claim_types')
    op.drop_table('claim_types')
    op.drop_index(op.f('ix_case_statuses_updated_by'), table_name='case_statuses')
    op.drop_index(op.f('ix_case_statuses_tenant_id'), table_name='case_statuses')
    op.drop_index(op.f('ix_case_statuses_created_by'), table_name='case_statuses')
    op.drop_table('case_statuses')
    # ### end Alembic commands ###
