"""Added claim questionaires

Revision ID: 96d86f337bc2
Revises: 2be1760b7e48
Create Date: 2025-09-09 02:14:28.723232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d86f337bc2'
down_revision: Union[str, None] = '2be1760b7e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_questionnaires',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('witness_sign', sa.String(length=255), nullable=True),
    sa.Column('officer_sign', sa.String(length=255), nullable=True),
    sa.Column('witness_name', sa.String(length=255), nullable=True),
    sa.Column('officer_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_witness', sa.DateTime(), nullable=True),
    sa.Column('date_of_officer', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_questionnaires_claim_id'), 'claim_questionnaires', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_questionnaires_created_by'), 'claim_questionnaires', ['created_by'], unique=False)
    op.create_index(op.f('ix_claim_questionnaires_id'), 'claim_questionnaires', ['id'], unique=False)
    op.create_index(op.f('ix_claim_questionnaires_updated_by'), 'claim_questionnaires', ['updated_by'], unique=False)
    op.add_column('questionnaires', sa.Column('claim_questionnaire_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_questionnaires_claim_id'), table_name='questionnaires')
    op.create_index(op.f('ix_questionnaires_claim_questionnaire_id'), 'questionnaires', ['claim_questionnaire_id'], unique=False)
    op.drop_constraint(op.f('questionnaires_claim_id_fkey'), 'questionnaires', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaires', 'claim_questionnaires', ['claim_questionnaire_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questionnaires', 'claim_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaires_claim_id_fkey'), 'questionnaires', 'claims', ['claim_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_questionnaires_claim_questionnaire_id'), table_name='questionnaires')
    op.create_index(op.f('ix_questionnaires_claim_id'), 'questionnaires', ['claim_id'], unique=False)
    op.drop_column('questionnaires', 'claim_questionnaire_id')
    op.drop_index(op.f('ix_claim_questionnaires_updated_by'), table_name='claim_questionnaires')
    op.drop_index(op.f('ix_claim_questionnaires_id'), table_name='claim_questionnaires')
    op.drop_index(op.f('ix_claim_questionnaires_created_by'), table_name='claim_questionnaires')
    op.drop_index(op.f('ix_claim_questionnaires_claim_id'), table_name='claim_questionnaires')
    op.drop_table('claim_questionnaires')
    # ### end Alembic commands ###
