"""borough and third party table

Revision ID: 9b6b327ba50a
Revises: 598e15b0a93f
Create Date: 2025-08-27 08:04:43.824303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6b327ba50a'
down_revision: Union[str, None] = '598e15b0a93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borough',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('borough_name', sa.String(length=200), nullable=False),
    sa.Column('taxi_type_id', sa.Integer(), nullable=True),
    sa.Column('client_badge_number', sa.String(length=200), nullable=False),
    sa.Column('badge_expiration_date', sa.Date(), nullable=False),
    sa.Column('vehicle_badge_number', sa.String(length=200), nullable=False),
    sa.Column('any_other_borough', sa.Boolean(), nullable=True),
    sa.Column('other_borough_name', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_vehicle_id'], ['client_vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taxi_type_id'], ['taxi_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borough_client_vehicle_id'), 'borough', ['client_vehicle_id'], unique=False)
    op.create_index(op.f('ix_borough_created_by'), 'borough', ['created_by'], unique=False)
    op.create_index(op.f('ix_borough_taxi_type_id'), 'borough', ['taxi_type_id'], unique=False)
    op.create_index(op.f('ix_borough_tenant_id'), 'borough', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_borough_updated_by'), 'borough', ['updated_by'], unique=False)
    op.create_table('third_party_vehicles',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('registration', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=200), nullable=True),
    sa.Column('images_available', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_vehicle_id'], ['client_vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_vehicles_client_vehicle_id'), 'third_party_vehicles', ['client_vehicle_id'], unique=False)
    op.create_index(op.f('ix_third_party_vehicles_created_by'), 'third_party_vehicles', ['created_by'], unique=False)
    op.create_index(op.f('ix_third_party_vehicles_id'), 'third_party_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_third_party_vehicles_updated_by'), 'third_party_vehicles', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_party_vehicles_updated_by'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_id'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_created_by'), table_name='third_party_vehicles')
    op.drop_index(op.f('ix_third_party_vehicles_client_vehicle_id'), table_name='third_party_vehicles')
    op.drop_table('third_party_vehicles')
    op.drop_index(op.f('ix_borough_updated_by'), table_name='borough')
    op.drop_index(op.f('ix_borough_tenant_id'), table_name='borough')
    op.drop_index(op.f('ix_borough_taxi_type_id'), table_name='borough')
    op.drop_index(op.f('ix_borough_created_by'), table_name='borough')
    op.drop_index(op.f('ix_borough_client_vehicle_id'), table_name='borough')
    op.drop_table('borough')
    # ### end Alembic commands ###
