"""sync all model changes

Revision ID: a15c56c314cf
Revises: 1a2419bd4a97
Create Date: 2026-02-18 03:10:50.666744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15c56c314cf'
down_revision: Union[str, None] = '1a2419bd4a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'non_fault_accident',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('claims', 'any_passengers',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('claims', 'client_injured',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'client_injured',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('claims', 'any_passengers',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('claims', 'non_fault_accident',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
