"""sync all model changes

Revision ID: a8ad4eac0490
Revises: 24ed5fff34ee
Create Date: 2026-02-17 19:39:46.878464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8ad4eac0490'
down_revision: Union[str, None] = '24ed5fff34ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_tenants_created_by'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_updated_by'), table_name='tenants')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.drop_constraint(op.f('tenants_created_by_fkey'), 'tenants', type_='foreignkey')
    op.drop_constraint(op.f('tenants_updated_by_fkey'), 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'is_deleted')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('tenants', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tenants_updated_by_fkey'), 'tenants', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('tenants_created_by_fkey'), 'tenants', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.create_index(op.f('ix_tenants_updated_by'), 'tenants', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_created_by'), 'tenants', ['created_by'], unique=False)
    op.alter_column('questionnaires', 'claim_questionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
