"""sync_all_model_changes

Revision ID: ab0fc81c4968
Revises: 7346658a9075
Create Date: 2026-03-12 15:47:26.736893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0fc81c4968'
down_revision: Union[str, None] = '7346658a9075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accident_details', 'condition',
               existing_type=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accident_details', 'condition',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
