"""update client_detail and add police detail table

Revision ID: ae2091403f79
Revises: 9b6b327ba50a
Create Date: 2025-09-01 21:18:51.608841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2091403f79'
down_revision: Union[str, None] = '9b6b327ba50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

person_role_enum = sa.Enum('CLIENT', 'PASSENGER', 'WITNESS', name='personroleenum')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_details',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reference_no', sa.String(length=200), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('station_address', sa.String(length=200), nullable=False),
    sa.Column('incident_report_taken', sa.Boolean(), nullable=False),
    sa.Column('report_received_date', sa.Date(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('accident_detail_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accident_detail_id'], ['accident_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    person_role_enum.create(op.get_bind(), checkfirst=True)
    op.create_index(op.f('ix_police_details_accident_detail_id'), 'police_details', ['accident_detail_id'], unique=False)
    op.create_index(op.f('ix_police_details_created_by'), 'police_details', ['created_by'], unique=False)
    op.create_index(op.f('ix_police_details_id'), 'police_details', ['id'], unique=False)
    op.create_index(op.f('ix_police_details_updated_by'), 'police_details', ['updated_by'], unique=False)
    op.add_column('client_details', sa.Column('role',person_role_enum, nullable=False))
    op.add_column('client_details', sa.Column('accident_detail_id', sa.Integer(), nullable=True))
    op.alter_column('client_details', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('client_details', 'ni_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('client_details', 'country',
               existing_type=postgresql.ENUM('AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KH', 'CM', 'CA', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CR', 'HR', 'CU', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TO', 'TT', 'TN', 'TM', 'TR', 'TV', 'UG', 'UA', 'AE', 'UK', 'US', 'UY', 'UZ', 'VU', 'VA', 'VE', 'VN', 'YE', 'ZM', 'ZW', name='country_code_enum'),
               nullable=True)
    op.alter_column('client_details', 'day_driver',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'sort_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('client_details', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('client_details', 'ci_vat_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'is_vulnerable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'speaks_clear_english',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_details', 'contact_via_alternative_person',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_client_details_accident_detail_id'), 'client_details', ['accident_detail_id'], unique=False)
    op.create_index(op.f('ix_client_details_role'), 'client_details', ['role'], unique=False)
    op.create_foreign_key(None, 'client_details', 'accident_details', ['accident_detail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_details', type_='foreignkey')
    op.drop_index(op.f('ix_client_details_role'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_accident_detail_id'), table_name='client_details')
    op.alter_column('client_details', 'contact_via_alternative_person',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'speaks_clear_english',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'is_vulnerable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'ci_vat_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('client_details', 'sort_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('client_details', 'day_driver',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('client_details', 'country',
               existing_type=postgresql.ENUM('AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CV', 'KH', 'CM', 'CA', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CR', 'HR', 'CU', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TO', 'TT', 'TN', 'TM', 'TR', 'TV', 'UG', 'UA', 'AE', 'UK', 'US', 'UY', 'UZ', 'VU', 'VA', 'VE', 'VN', 'YE', 'ZM', 'ZW', name='country_code_enum'),
               nullable=False)
    op.alter_column('client_details', 'ni_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('client_details', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('client_details', 'accident_detail_id')
    op.drop_column('client_details', 'role')
    person_role_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_police_details_updated_by'), table_name='police_details')
    op.drop_index(op.f('ix_police_details_id'), table_name='police_details')
    op.drop_index(op.f('ix_police_details_created_by'), table_name='police_details')
    op.drop_index(op.f('ix_police_details_accident_detail_id'), table_name='police_details')
    op.drop_table('police_details')
    # ### end Alembic commands ###
