"""auto add new columns to claim

Revision ID: ce6685e98d64
Revises: 950dd262a77d
Create Date: 2025-08-21 22:21:42.555623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6685e98d64'
down_revision: Union[str, None] = '950dd262a77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=False),
    sa.Column('home_tel', sa.String(length=20), nullable=True),
    sa.Column('mobile_tel', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_created_by'), 'addresses', ['created_by'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_updated_by'), 'addresses', ['updated_by'], unique=False)
    op.create_table('driver_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_hire_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('on_hire_paid_on', sa.Date(), nullable=True),
    sa.Column('congestion_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off_hire_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off_hire_paid_on', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_commissions_created_by'), 'driver_commissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_driver_commissions_id'), 'driver_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_driver_commissions_tenant_id'), 'driver_commissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_driver_commissions_updated_by'), 'driver_commissions', ['updated_by'], unique=False)
    op.create_table('referrer_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_hire_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('on_hire_paid_on', sa.Date(), nullable=True),
    sa.Column('off_hire_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off_hire_paid_on', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrer_commissions_created_by'), 'referrer_commissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_referrer_commissions_id'), 'referrer_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_referrer_commissions_tenant_id'), 'referrer_commissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_referrer_commissions_updated_by'), 'referrer_commissions', ['updated_by'], unique=False)
    op.create_table('accident_details',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition', sa.Enum('DRY', 'RAINY', 'STROMY', 'CLOUDY', 'SUNNY', name='weathertypeenum'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('any_passenger', sa.Boolean(), nullable=False),
    sa.Column('passenger_no', sa.Integer(), nullable=True),
    sa.Column('witness', sa.Boolean(), nullable=False),
    sa.Column('police_attend', sa.Boolean(), nullable=False),
    sa.Column('dash_footage', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_details_claim_id'), 'accident_details', ['claim_id'], unique=False)
    op.create_index(op.f('ix_accident_details_created_by'), 'accident_details', ['created_by'], unique=False)
    op.create_index(op.f('ix_accident_details_id'), 'accident_details', ['id'], unique=False)
    op.create_index(op.f('ix_accident_details_updated_by'), 'accident_details', ['updated_by'], unique=False)
    op.create_table('client_details',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('ni_number', sa.String(length=50), nullable=False),
    sa.Column('driver_code', sa.String(length=50), nullable=True),
    sa.Column('day_driver', sa.Boolean(), nullable=False),
    sa.Column('driver_base', sa.String(length=100), nullable=True),
    sa.Column('sort_code', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_details_note', sa.Text(), nullable=True),
    sa.Column('ci_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('is_vulnerable', sa.Boolean(), nullable=False),
    sa.Column('vulnerable_note', sa.Text(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('client_language', sa.String(length=50), nullable=True),
    sa.Column('speaks_clear_english', sa.Boolean(), nullable=False),
    sa.Column('contact_via_alternative_person', sa.Boolean(), nullable=False),
    sa.Column('alter_person', sa.String(length=100), nullable=True),
    sa.Column('alter_number', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('ni_number')
    )
    op.create_index(op.f('ix_client_details_address_id'), 'client_details', ['address_id'], unique=False)
    op.create_index(op.f('ix_client_details_claim_id'), 'client_details', ['claim_id'], unique=False)
    op.create_index(op.f('ix_client_details_created_by'), 'client_details', ['created_by'], unique=False)
    op.create_index(op.f('ix_client_details_id'), 'client_details', ['id'], unique=False)
    op.create_index(op.f('ix_client_details_tenant_id'), 'client_details', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_client_details_updated_by'), 'client_details', ['updated_by'], unique=False)
    op.create_table('referrers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('solicitor', sa.String(length=200), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('primary_contact_number', sa.String(length=50), nullable=False),
    sa.Column('third_party_capture', sa.String(length=200), nullable=False),
    sa.Column('driver_commission_id', sa.Integer(), nullable=False),
    sa.Column('referrer_commission_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_commission_id'], ['driver_commissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_commission_id'], ['referrer_commissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrers_claim_id'), 'referrers', ['claim_id'], unique=False)
    op.create_index(op.f('ix_referrers_created_by'), 'referrers', ['created_by'], unique=False)
    op.create_index(op.f('ix_referrers_driver_commission_id'), 'referrers', ['driver_commission_id'], unique=False)
    op.create_index(op.f('ix_referrers_id'), 'referrers', ['id'], unique=False)
    op.create_index(op.f('ix_referrers_referrer_commission_id'), 'referrers', ['referrer_commission_id'], unique=False)
    op.create_index(op.f('ix_referrers_tenant_id'), 'referrers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_referrers_updated_by'), 'referrers', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrers_updated_by'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_tenant_id'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_referrer_commission_id'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_id'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_driver_commission_id'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_created_by'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_claim_id'), table_name='referrers')
    op.drop_table('referrers')
    op.drop_index(op.f('ix_client_details_updated_by'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_tenant_id'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_id'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_created_by'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_claim_id'), table_name='client_details')
    op.drop_index(op.f('ix_client_details_address_id'), table_name='client_details')
    op.drop_table('client_details')
    op.drop_index(op.f('ix_accident_details_updated_by'), table_name='accident_details')
    op.drop_index(op.f('ix_accident_details_id'), table_name='accident_details')
    op.drop_index(op.f('ix_accident_details_created_by'), table_name='accident_details')
    op.drop_index(op.f('ix_accident_details_claim_id'), table_name='accident_details')
    op.drop_table('accident_details')
    op.drop_index(op.f('ix_referrer_commissions_updated_by'), table_name='referrer_commissions')
    op.drop_index(op.f('ix_referrer_commissions_tenant_id'), table_name='referrer_commissions')
    op.drop_index(op.f('ix_referrer_commissions_id'), table_name='referrer_commissions')
    op.drop_index(op.f('ix_referrer_commissions_created_by'), table_name='referrer_commissions')
    op.drop_table('referrer_commissions')
    op.drop_index(op.f('ix_driver_commissions_updated_by'), table_name='driver_commissions')
    op.drop_index(op.f('ix_driver_commissions_tenant_id'), table_name='driver_commissions')
    op.drop_index(op.f('ix_driver_commissions_id'), table_name='driver_commissions')
    op.drop_index(op.f('ix_driver_commissions_created_by'), table_name='driver_commissions')
    op.drop_table('driver_commissions')
    op.drop_index(op.f('ix_addresses_updated_by'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_created_by'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
