"""update police detail table

Revision ID: d5b7117504ef
Revises: ae2091403f79
Create Date: 2025-09-02 19:12:28.298916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b7117504ef'
down_revision: Union[str, None] = 'ae2091403f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_details', sa.Column('claim_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_police_details_accident_detail_id'), table_name='police_details')
    op.create_index(op.f('ix_police_details_claim_id'), 'police_details', ['claim_id'], unique=False)
    op.drop_constraint(op.f('police_details_accident_detail_id_fkey'), 'police_details', type_='foreignkey')
    op.create_foreign_key(None, 'police_details', 'claims', ['claim_id'], ['id'], ondelete='CASCADE')
    op.drop_column('police_details', 'accident_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_details', sa.Column('accident_detail_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'police_details', type_='foreignkey')
    op.create_foreign_key(op.f('police_details_accident_detail_id_fkey'), 'police_details', 'accident_details', ['accident_detail_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_police_details_claim_id'), table_name='police_details')
    op.create_index(op.f('ix_police_details_accident_detail_id'), 'police_details', ['accident_detail_id'], unique=False)
    op.drop_column('police_details', 'claim_id')
    # ### end Alembic commands ###
